"""
ORM models for the AI Study Plan Generator.

Mirrors `src/types/planner.ts`. `StudyTask` rows are (re)generated by
`app/services/study_planner.py` whenever a triggering signal fires — the
frontend's `useStudyPlan.regenerate(trigger)` simulates the same event
names this module reacts to server-side.
"""

from __future__ import annotations

import enum
import uuid
from datetime import date, datetime

from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.db import Base


def _uuid() -> str:
    return str(uuid.uuid4())


class StudyTaskType(str, enum.Enum):
    lecture = "lecture"
    revision = "revision"
    practice = "practice"
    quiz = "quiz"
    flashcards = "flashcards"
    assignment = "assignment"
    break_ = "break"
    exam_prep = "exam-prep"


class StudyTaskPriority(str, enum.Enum):
    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


class PlanRegenerationTrigger(str, enum.Enum):
    """
    Every event that should cause the planner to re-run. Handlers for each
    of these are registered in app/services/study_planner.py and fired
    from the relevant API routes (e.g. POST /quizzes/{id}/submit calls
    `regenerate(trigger=PlanRegenerationTrigger.quiz_completed)`).
    """

    quiz_completed = "quiz-completed"
    lecture_uploaded = "lecture-uploaded"
    exam_added = "exam-added"
    assignment_submitted = "assignment-submitted"
    performance_improved = "performance-improved"
    performance_declined = "performance-declined"


class StudyTask(Base):
    __tablename__ = "study_tasks"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    owner_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("users.id"), index=True)

    title: Mapped[str] = mapped_column(String(255))
    subject: Mapped[str] = mapped_column(String(128), default="")
    type: Mapped[StudyTaskType] = mapped_column(Enum(StudyTaskType))
    priority: Mapped[StudyTaskPriority] = mapped_column(Enum(StudyTaskPriority))

    scheduled_date: Mapped[date] = mapped_column(DateTime)
    start_minute: Mapped[int] = mapped_column(Integer)
    duration_minutes: Mapped[int] = mapped_column(Integer)
    done: Mapped[bool] = mapped_column(Boolean, default=False)

    ai_reason: Mapped[str] = mapped_column(Text)

    # Links this task back to the source it was generated from, so
    # completing it (or the source changing) can retrigger planning.
    source_lecture_id: Mapped[str | None] = mapped_column(UUID(as_uuid=False), nullable=True)
    source_exam_id: Mapped[str | None] = mapped_column(UUID(as_uuid=False), nullable=True)

    generated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    generation_trigger: Mapped[PlanRegenerationTrigger | None] = mapped_column(
        Enum(PlanRegenerationTrigger), nullable=True
    )


class UpcomingExam(Base):
    __tablename__ = "upcoming_exams"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    owner_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("users.id"), index=True)

    subject: Mapped[str] = mapped_column(String(128))
    title: Mapped[str] = mapped_column(String(255))
    exam_date: Mapped[date] = mapped_column(DateTime)
    readiness: Mapped[int] = mapped_column(Integer, default=0)
