"""Initial migration

Revision ID: fa94e7c3c032
Revises: 
Create Date: 2026-07-30 14:04:35.356620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa94e7c3c032'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=True)
    op.create_table('faculties',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('university_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculties_university_id'), 'faculties', ['university_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('faculty_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_faculty_id'), 'departments', ['faculty_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('university_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('faculty_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('department_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('academic_year', sa.Enum('year_1', 'year_2', 'year_3', 'year_4', 'year_5', 'graduate', name='academicyear'), nullable=True),
    sa.Column('semester', sa.Enum('semester_1', 'semester_2', 'summer', name='semester'), nullable=True),
    sa.Column('student_id_number', sa.String(length=64), nullable=True),
    sa.Column('study_goals', postgresql.ARRAY(String()), nullable=False),
    sa.Column('academic_identity_locked', sa.Boolean(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('badges', postgresql.ARRAY(String()), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_study_date', sa.Date(), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_faculty_id'), 'users', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_users_university_id'), 'users', ['university_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('friend_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friendships_friend_id'), 'friendships', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friendships_user_id'), 'friendships', ['user_id'], unique=False)
    op.create_table('ranking_snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scope', sa.Enum('university', 'faculty', 'department', 'academic_year', 'course', 'friends', name='rankingscope'), nullable=False),
    sa.Column('scope_value', sa.String(length=255), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('xp_in_period', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_snapshots_rank'), 'ranking_snapshots', ['rank'], unique=False)
    op.create_index(op.f('ix_ranking_snapshots_scope'), 'ranking_snapshots', ['scope'], unique=False)
    op.create_index(op.f('ix_ranking_snapshots_scope_value'), 'ranking_snapshots', ['scope_value'], unique=False)
    op.create_index(op.f('ix_ranking_snapshots_timeframe'), 'ranking_snapshots', ['timeframe'], unique=False)
    op.create_index(op.f('ix_ranking_snapshots_user_id'), 'ranking_snapshots', ['user_id'], unique=False)
    op.create_table('study_tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('lecture', 'revision', 'practice', 'quiz', 'flashcards', 'assignment', 'break_', 'exam_prep', name='studytasktype'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='studytaskpriority'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('ai_reason', sa.Text(), nullable=False),
    sa.Column('source_lecture_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_exam_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generation_trigger', sa.Enum('quiz_completed', 'lecture_uploaded', 'exam_added', 'assignment_submitted', 'performance_improved', 'performance_declined', name='planregenerationtrigger'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_tasks_owner_id'), 'study_tasks', ['owner_id'], unique=False)
    op.create_table('upcoming_exams',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=False),
    sa.Column('readiness', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upcoming_exams_owner_id'), 'upcoming_exams', ['owner_id'], unique=False)
    op.create_table('video_lectures',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('course_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('upload', 'zoom', 'teams', 'meet', 'screen_recording', 'lecture', name='videosourcetype'), nullable=False),
    sa.Column('state', sa.Enum('queued', 'processing', 'ready', 'failed', name='videoprocessingstate'), nullable=False),
    sa.Column('original_storage_key', sa.String(length=512), nullable=False),
    sa.Column('optimized_storage_key', sa.String(length=512), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('optimized_duration_sec', sa.Float(), nullable=False),
    sa.Column('learning_efficiency_score', sa.Integer(), nullable=False),
    sa.Column('current_stage_index', sa.Integer(), nullable=False),
    sa.Column('pipeline_state', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_lectures_owner_id'), 'video_lectures', ['owner_id'], unique=False)
    op.create_table('video_chapters',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lecture_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('exam_importance', sa.Integer(), nullable=False),
    sa.Column('estimated_study_minutes', sa.Integer(), nullable=False),
    sa.Column('key_concepts', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('formulas', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('exam_tips', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['video_lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_chapters_lecture_id'), 'video_chapters', ['lecture_id'], unique=False)
    op.create_table('video_silence_segments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lecture_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['video_lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_silence_segments_lecture_id'), 'video_silence_segments', ['lecture_id'], unique=False)
    op.create_table('video_flashcards',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lecture_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chapter_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['video_chapters.id'], ),
    sa.ForeignKeyConstraint(['lecture_id'], ['video_lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_flashcards_lecture_id'), 'video_flashcards', ['lecture_id'], unique=False)
    op.create_table('video_quiz_questions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lecture_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chapter_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['video_chapters.id'], ),
    sa.ForeignKeyConstraint(['lecture_id'], ['video_lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_quiz_questions_lecture_id'), 'video_quiz_questions', ['lecture_id'], unique=False)
    op.create_table('video_transcript_segments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lecture_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chapter_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('speaker', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['video_chapters.id'], ),
    sa.ForeignKeyConstraint(['lecture_id'], ['video_lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_transcript_segments_lecture_id'), 'video_transcript_segments', ['lecture_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_transcript_segments_lecture_id'), table_name='video_transcript_segments')
    op.drop_table('video_transcript_segments')
    op.drop_index(op.f('ix_video_quiz_questions_lecture_id'), table_name='video_quiz_questions')
    op.drop_table('video_quiz_questions')
    op.drop_index(op.f('ix_video_flashcards_lecture_id'), table_name='video_flashcards')
    op.drop_table('video_flashcards')
    op.drop_index(op.f('ix_video_silence_segments_lecture_id'), table_name='video_silence_segments')
    op.drop_table('video_silence_segments')
    op.drop_index(op.f('ix_video_chapters_lecture_id'), table_name='video_chapters')
    op.drop_table('video_chapters')
    op.drop_index(op.f('ix_video_lectures_owner_id'), table_name='video_lectures')
    op.drop_table('video_lectures')
    op.drop_index(op.f('ix_upcoming_exams_owner_id'), table_name='upcoming_exams')
    op.drop_table('upcoming_exams')
    op.drop_index(op.f('ix_study_tasks_owner_id'), table_name='study_tasks')
    op.drop_table('study_tasks')
    op.drop_index(op.f('ix_ranking_snapshots_user_id'), table_name='ranking_snapshots')
    op.drop_index(op.f('ix_ranking_snapshots_timeframe'), table_name='ranking_snapshots')
    op.drop_index(op.f('ix_ranking_snapshots_scope_value'), table_name='ranking_snapshots')
    op.drop_index(op.f('ix_ranking_snapshots_scope'), table_name='ranking_snapshots')
    op.drop_index(op.f('ix_ranking_snapshots_rank'), table_name='ranking_snapshots')
    op.drop_table('ranking_snapshots')
    op.drop_index(op.f('ix_friendships_user_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_friend_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_users_university_id'), table_name='users')
    op.drop_index(op.f('ix_users_faculty_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_faculty_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_faculties_university_id'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_table('universities')
    op.drop_table('courses')
    # ### end Alembic commands ###
